## recode activities according to data dictionary
## https://www.atusdata.org/atus-action/downloads/extract_files/atus_00004.xml
data <- data %>% 
  mutate(activity_general = case_when(
    ACTIVITY %in% c(10000:19999) ~ "Personal Care",
    ACTIVITY %in% c(20000:29999) ~ "Household Activities",
    ACTIVITY %in% c(30000:39999) ~ "Caring for and Helping Household Members",
    ACTIVITY %in% c(40000:49999) ~ "Caring for and Helping Non-Household Members",
    ACTIVITY %in% c(50000:59999) ~ "Work and Work-Related Activities",
    ACTIVITY %in% c(60000:69999) ~ "Education",
    ACTIVITY %in% c(70000:79999) ~ "Consumer Purchases",
    ACTIVITY %in% c(80000:89999) ~ "Professional and Personal Care Services",
    ACTIVITY %in% c(90000:99999) ~ "Household Services",
    ACTIVITY %in% c(100000:109999) ~ "Government Services and Civic Obligations",
    ACTIVITY %in% c(110000:119999) ~ "Eating and Drinking",
    ACTIVITY %in% c(120000:129999) ~ "SocializingRelaxingand Leisure",
    ACTIVITY %in% c(130000:139999) ~ "SportsExerciseand Recreation",
    ACTIVITY %in% c(140000:149999) ~ "Religious and Spiritual Activities",
    ACTIVITY %in% c(150000:159999) ~ "Volunteer Activities",
    ACTIVITY %in% c(160000:169999) ~ "Telephone Calls",
    ACTIVITY %in% c(180000:189999) ~ "Traveling",
    ACTIVITY > 500000 ~ "Unable to Code"
  ))

data <- data %>% 
  mutate(activity_specific = case_when(
    ACTIVITY == 010000 ~ "Personal Care",
    ACTIVITY == 010100 ~ "Sleeping",
    ACTIVITY == 010101 ~ "Sleeping",
    ACTIVITY == 010102 ~ "Sleeplessness",
    ACTIVITY == 010199 ~ "Sleeping",
    ACTIVITY == 010200 ~ "Grooming",
    ACTIVITY == 010201 ~ "Washingdressing and grooming oneself",
    ACTIVITY == 010299 ~ "Grooming",
    ACTIVITY == 010300 ~ "Health-Related Self Care",
    ACTIVITY == 010301 ~ "Health-related self care",
    ACTIVITY == 010399 ~ "Self care",
    ACTIVITY == 010400 ~ "Personal Activities",
    ACTIVITY == 010401 ~ "Personal/Private activities",
    ACTIVITY == 010499 ~ "Personal activities",
    ACTIVITY == 010500 ~ "Personal Care Emergencies",
    ACTIVITY == 010501 ~ "Personal emergencies",
    ACTIVITY == 010599 ~ "Personal care emergencies",
    ACTIVITY == 019900 ~ "Personal Care",
    ACTIVITY == 019999 ~ "Personal care",
    ACTIVITY == 020000 ~ "Household Activities",
    ACTIVITY == 020100 ~ "Housework",
    ACTIVITY == 020101 ~ "Interior cleaning",
    ACTIVITY == 020102 ~ "Laundry",
    ACTIVITY == 020103 ~ "Sewingrepairingand maintaining textiles",
    ACTIVITY == 020104 ~ "Storing interior household items, food",
    ACTIVITY == 020199 ~ "Housework",
    ACTIVITY == 020200 ~ "Food and Drink PreparationPresentationand Clean-up",
    ACTIVITY == 020201 ~ "Food and drink preparation",
    ACTIVITY == 020202 ~ "Food presentation",
    ACTIVITY == 020203 ~ "Kitchen and food clean-up",
    ACTIVITY == 020299 ~ "Food and drink prepserving and clean-up",
    ACTIVITY == 020300 ~ "Interior MaintenanceRepairand Decoration",
    ACTIVITY == 020301 ~ "Interior arrangementdecorationand repairs",
    ACTIVITY == 020302 ~ "Building and repairing furniture",
    ACTIVITY == 020303 ~ "Heating and cooling",
    ACTIVITY == 020399 ~ "Interior maintenancerepairand decoration",
    ACTIVITY == 020400 ~ "Exterior MaintenanceRepairand Decoration",
    ACTIVITY == 020401 ~ "Exterior cleaning",
    ACTIVITY == 020402 ~ "Exterior repairimprovementsand decoration",
    ACTIVITY == 020499 ~ "Exterior maintenancerepair and decoration",
    ACTIVITY == 020500 ~ "LawnGardenand Houseplants",
    ACTIVITY == 020501 ~ "Lawngardenand houseplant care",
    ACTIVITY == 020502 ~ "Pondspoolsand hot tubs",
    ACTIVITY == 020599 ~ "Lawn and garden",
    ACTIVITY == 020600 ~ "Animals and Pets",
    ACTIVITY == 020601 ~ "Care for animals and pets (not veterinary care)",
    ACTIVITY == 020602 ~ "Care for animals and pets (not veterinary care) (2008+)",
    ACTIVITY == 020603 ~ "Walkingexercisingplaying with animals (2008+)",
    ACTIVITY == 020699 ~ "Pet and animal care",
    ACTIVITY == 020700 ~ "Vehicles",
    ACTIVITY == 020701 ~ "Vehicle repair and maintenance (by self)",
    ACTIVITY == 020799 ~ "Vehicles",
    ACTIVITY == 020800 ~ "AppliancesToolsand Toys",
    ACTIVITY == 020801 ~ "Apptooltoy set-uprepairand maint (by self)",
    ACTIVITY == 020899 ~ "Appliances and tools",
    ACTIVITY == 020900 ~ "Household Management",
    ACTIVITY == 020901 ~ "Financial management",
    ACTIVITY == 020902 ~ "Household and personal organization and planning",
    ACTIVITY == 020903 ~ "HH and personal mail and messages (except e-mail)",
    ACTIVITY == 020904 ~ "HH and personal e-mail and messages",
    ACTIVITY == 020905 ~ "Home security",
    ACTIVITY == 020999 ~ "Household management",
    ACTIVITY == 029900 ~ "Household activities",
    ACTIVITY == 029999 ~ "Household activities",
    ACTIVITY == 030000 ~ "Caring for and Helping Household Members",
    ACTIVITY == 030100 ~ "Caring for and Helping Household Children",
    ACTIVITY == 030101 ~ "Physical care for household children",
    ACTIVITY == 030102 ~ "Reading to/with household children",
    ACTIVITY == 030103 ~ "Playing with household childrennot sports",
    ACTIVITY == 030104 ~ "Arts and crafts with household children",
    ACTIVITY == 030105 ~ "Playing sports with household children",
    ACTIVITY == 030106 ~ "Talking with/listening to household children",
    ACTIVITY == 030107 ~ "Helping or teaching household children",
    ACTIVITY == 030108 ~ "Organization and planning for household children",
    ACTIVITY == 030109 ~ "Looking after household children (as a primary activity)",
    ACTIVITY == 030110 ~ "Attending household childrens events",
    ACTIVITY == 030111 ~ "Waiting for/with household children",
    ACTIVITY == 030112 ~ "Picking up/dropping off household children",
    ACTIVITY == 030199 ~ "Caring for and helping household children",
    ACTIVITY == 030200 ~ "Activities Related to Household Childrens Education",
    ACTIVITY == 030201 ~ "Homework (household children)",
    ACTIVITY == 030202 ~ "Meetings and school conferences (household children)",
    ACTIVITY == 030203 ~ "Home schooling of household children",
    ACTIVITY == 030204 ~ "Waiting associated with household childrens education",
    ACTIVITY == 030299 ~ "Activities related to household childs education",
    ACTIVITY == 030300 ~ "Activities Related to Household Childrens Health",
    ACTIVITY == 030301 ~ "Providing medical care to household children",
    ACTIVITY == 030302 ~ "Obtaining medical care for household children",
    ACTIVITY == 030303 ~ "Waiting associated with household childrens health",
    ACTIVITY == 030399 ~ "Activities related to household childs health",
    ACTIVITY == 030400 ~ "Caring for Household Adults",
    ACTIVITY == 030401 ~ "Physical care for household adults",
    ACTIVITY == 030402 ~ "Looking after household adult (as a primary activity)",
    ACTIVITY == 030403 ~ "Providing medical care to household adult",
    ACTIVITY == 030404 ~ "Obtaining medical and care services for household adult",
    ACTIVITY == 030405 ~ "Waiting associated with caring for household adults",
    ACTIVITY == 030499 ~ "Caring for household adults",
    ACTIVITY == 030500 ~ "Helping Household Adults",
    ACTIVITY == 030501 ~ "Helping household adults",
    ACTIVITY == 030502 ~ "Organization and planning for household adults",
    ACTIVITY == 030503 ~ "Picking up/dropping off household adult",
    ACTIVITY == 030504 ~ "Waiting associated with helping household adults",
    ACTIVITY == 030599 ~ "Helping household adults",
    ACTIVITY == 039900 ~ "Caring for and Helping Household Members",
    ACTIVITY == 039999 ~ "Caring for and helping household members",
    ACTIVITY == 040000 ~ "Caring for and Helping Non-Household Members",
    ACTIVITY == 040100 ~ "Caring for and Helping Non-Household Children",
    ACTIVITY == 040101 ~ "Physical care for Non-Household children",
    ACTIVITY == 040102 ~ "Reading to/with Non-Household children",
    ACTIVITY == 040103 ~ "Playing with Non-Household childrennot sports",
    ACTIVITY == 040104 ~ "Arts and crafts with Non-Household children",
    ACTIVITY == 040105 ~ "Playing sports with Non-Household children",
    ACTIVITY == 040106 ~ "Talking with/listening to Non-Household children",
    ACTIVITY == 040107 ~ "Helping or teaching Non-Household children",
    ACTIVITY == 040108 ~ "Organization and planning for Non-Household children",
    ACTIVITY == 040109 ~ "Looking after Non-Household children (as primary activity)",
    ACTIVITY == 040110 ~ "Attending Non-Household childrens events",
    ACTIVITY == 040111 ~ "Waiting for/with Non-Household children",
    ACTIVITY == 040112 ~ "Dropping off/picking up Non-Household children",
    ACTIVITY == 040199 ~ "Caring for and helping Non-Household children",
    ACTIVITY == 040200 ~ "Activities Related to Non-Household Childrens Education",
    ACTIVITY == 040201 ~ "Homework (Non-Household children)",
    ACTIVITY == 040202 ~ "Mtgs and school conferences (Non-Household children)",
    ACTIVITY == 040203 ~ "Home schooling of Non-Household children",
    ACTIVITY == 040204 ~ "Waiting assoc w/ Non-Household childrens education",
    ACTIVITY == 040299 ~ "Activities related to Non-Household childs educ.",
    ACTIVITY == 040300 ~ "Activities Related to Non-Household Childrens Health",
    ACTIVITY == 040301 ~ "Providing medical care to Non-Household children",
    ACTIVITY == 040302 ~ "Obtaining medical care for Non-Household children",
    ACTIVITY == 040303 ~ "Waiting associated with Non-Household childrens health",
    ACTIVITY == 040399 ~ "Activities related to Non-Household childs health",
    ACTIVITY == 040400 ~ "Caring for Non-Household Adults",
    ACTIVITY == 040401 ~ "Physical care for Non-Household adults",
    ACTIVITY == 040402 ~ "Looking after Non-Household adult (as a primary activity)",
    ACTIVITY == 040403 ~ "Providing medical care to Non-Household adult",
    ACTIVITY == 040404 ~ "Obtaining medical and care services for Non-Household adult",
    ACTIVITY == 040405 ~ "Waiting associated with caring for Non-Household adults",
    ACTIVITY == 040499 ~ "Caring for Non-Household adults",
    ACTIVITY == 040500 ~ "Helping Non-Household Adults",
    ACTIVITY == 040501 ~ "Hswrkcookingand shopping asstNon-Household adults",
    ACTIVITY == 040502 ~ "House and lawn maint and repair asstNon-Household adults",
    ACTIVITY == 040503 ~ "Animal and pet care assistance for Non-Household adults",
    ACTIVITY == 040504 ~ "Vehicle/appliance maint/repair asstNon-Household adults",
    ACTIVITY == 040505 ~ "Financial management assistant for Non-Household adults",
    ACTIVITY == 040506 ~ "Household management and paperwork asstNon-Household adults",
    ACTIVITY == 040507 ~ "Picking up/dropping off Non-Household adult",
    ACTIVITY == 040508 ~ "Waiting associated with helping Non-Household adults",
    ACTIVITY == 040599 ~ "Helping Non-Household adults",
    ACTIVITY == 049900 ~ "Caring for and Helping Non-Household Members",
    ACTIVITY == 049999 ~ "Caring for and helping Non-Household members",
    ACTIVITY == 050000 ~ "Work and Work-Related Activities",
    ACTIVITY == 050100 ~ "Working",
    ACTIVITY == 050101 ~ "Workmain job",
    ACTIVITY == 050102 ~ "Workother job(s)",
    ACTIVITY == 050103 ~ "Security procedures related to work",
    ACTIVITY == 050104 ~ "Waiting associated with working",
    ACTIVITY == 050199 ~ "Working",
    ACTIVITY == 050200 ~ "Work-Related Activities",
    ACTIVITY == 050201 ~ "Socializingrelaxingand leisure as part of job",
    ACTIVITY == 050202 ~ "Eating and drinking as part of job",
    ACTIVITY == 050203 ~ "Sports and exercise as part of job",
    ACTIVITY == 050204 ~ "Security procedures as part of job",
    ACTIVITY == 050205 ~ "Waiting associated with work-related activities",
    ACTIVITY == 050299 ~ "Work-related activities",
    ACTIVITY == 050300 ~ "Other Income-Generating Activities",
    ACTIVITY == 050301 ~ "Income-generating hobbiescraftsand food",
    ACTIVITY == 050302 ~ "Income-generating performances",
    ACTIVITY == 050303 ~ "Income-generating services",
    ACTIVITY == 050304 ~ "Income-generating rental property activities",
    ACTIVITY == 050305 ~ "Waiting assoc w/other income-generating acts",
    ACTIVITY == 050399 ~ "Other income-generating activities",
    ACTIVITY == 050400 ~ "Job Search and Interviewing",
    ACTIVITY == 050401 ~ "Job search activities",
    ACTIVITY == 050403 ~ "Job interviewing",
    ACTIVITY == 050404 ~ "Waiting associated with job search or interview",
    ACTIVITY == 050405 ~ "Sec. procedures related to job search/interviewing",
    ACTIVITY == 050499 ~ "Job search and Interviewing",
    ACTIVITY == 059900 ~ "Work and Work-Related Activities",
    ACTIVITY == 059999 ~ "Work and work-related activities",
    ACTIVITY == 060000 ~ "Education",
    ACTIVITY == 060100 ~ "Taking Class",
    ACTIVITY == 060101 ~ "Taking class for degreecertificationor license",
    ACTIVITY == 060102 ~ "Taking class for personal interest",
    ACTIVITY == 060103 ~ "Waiting associated with taking classes",
    ACTIVITY == 060104 ~ "Security procedures related to taking classes",
    ACTIVITY == 060199 ~ "Taking class",
    ACTIVITY == 060200 ~ "Extracurricular School Activities (except sports)",
    ACTIVITY == 060201 ~ "Extracurricular club activities",
    ACTIVITY == 060202 ~ "Extracurricular music and performance activities",
    ACTIVITY == 060203 ~ "Extracurricular student government activities",
    ACTIVITY == 060204 ~ "Waiting associated with extracurricular activities",
    ACTIVITY == 060299 ~ "Education-related extracurricular activities",
    ACTIVITY == 060300 ~ "Research or Homework",
    ACTIVITY == 060301 ~ "Rsrch/HW for class for degreecertor license",
    ACTIVITY == 060302 ~ "Research/homework for class for pers. interest",
    ACTIVITY == 060303 ~ "Waiting associated with research/homework",
    ACTIVITY == 060399 ~ "Research/homework ",
    ACTIVITY == 060400 ~ "Registration or Administrative Activities",
    ACTIVITY == 060401 ~ "Admin activities: class for degreecertor license",
    ACTIVITY == 060402 ~ "Admin activities: class for personal interest",
    ACTIVITY == 060403 ~ "Waiting assoc w/admin. activities (education)",
    ACTIVITY == 060499 ~ "Administrative for education",
    ACTIVITY == 069900 ~ "Education",
    ACTIVITY == 069999 ~ "Education",
    ACTIVITY == 070000 ~ "Consumer Purchases",
    ACTIVITY == 070100 ~ "Shopping (storetelephoneinternet)",
    ACTIVITY == 070101 ~ "Grocery shopping",
    ACTIVITY == 070102 ~ "Purchasing gas",
    ACTIVITY == 070103 ~ "Purchasing food (not groceries)",
    ACTIVITY == 070104 ~ "Shoppingexcept groceriesfood and gas",
    ACTIVITY == 070105 ~ "Waiting associated with shopping",
    ACTIVITY == 070199 ~ "Shopping",
    ACTIVITY == 070200 ~ "Researching Purchases",
    ACTIVITY == 070201 ~ "Comparison shopping",
    ACTIVITY == 070299 ~ "Researching purchases",
    ACTIVITY == 070300 ~ "Security Procedures Related to Consumer Purchases",
    ACTIVITY == 070301 ~ "Security procedures related to consumer purchases",
    ACTIVITY == 070399 ~ "Sec procedures related to cons purchases",
    ACTIVITY == 079900 ~ "Consumer Purchases",
    ACTIVITY == 079999 ~ "Consumer purchases",
    ACTIVITY == 080000 ~ "Professional and Personal Care Services",
    ACTIVITY == 080100 ~ "Childcare Services",
    ACTIVITY == 080101 ~ "Using paid childcare services",
    ACTIVITY == 080102 ~ "Waiting associated w/purchasing childcare services",
    ACTIVITY == 080199 ~ "Using paid childcare services",
    ACTIVITY == 080200 ~ "Financial Services and Banking",
    ACTIVITY == 080201 ~ "Banking",
    ACTIVITY == 080202 ~ "Using other financial services",
    ACTIVITY == 080203 ~ "Waiting associated w/banking/financial services",
    ACTIVITY == 080299 ~ "Using financial services and banking",
    ACTIVITY == 080300 ~ "Legal Services",
    ACTIVITY == 080301 ~ "Using legal services",
    ACTIVITY == 080302 ~ "Waiting associated with legal services",
    ACTIVITY == 080399 ~ "Using legal services",
    ACTIVITY == 080400 ~ "Medical and Care Services",
    ACTIVITY == 080401 ~ "Using health and care services outside the home",
    ACTIVITY == 080402 ~ "Using in-home health and care services",
    ACTIVITY == 080403 ~ "Waiting associated with medical services",
    ACTIVITY == 080499 ~ "Using medical services",
    ACTIVITY == 080500 ~ "Personal Care Services",
    ACTIVITY == 080501 ~ "Using personal care services",
    ACTIVITY == 080502 ~ "Waiting associated w/personal care services",
    ACTIVITY == 080599 ~ "Using personal care services",
    ACTIVITY == 080600 ~ "Real Estate",
    ACTIVITY == 080601 ~ "Activities related to purchasing/selling real estate",
    ACTIVITY == 080602 ~ "Waiting assoc w/purchasing/selling real estate",
    ACTIVITY == 080699 ~ "Using real estate services",
    ACTIVITY == 080700 ~ "Veterinary Services (excluding grooming)",
    ACTIVITY == 080701 ~ "Using veterinary services",
    ACTIVITY == 080702 ~ "Waiting associated with veterinary services",
    ACTIVITY == 080799 ~ "Using veterinary services",
    ACTIVITY == 080800 ~ "Security Procedures Related to Professional or Personal Services",
    ACTIVITY == 080801 ~ "Security procedures related to prof/personal services.",
    ACTIVITY == 080899 ~ "Sec procedures related to prof/personal services ",
    ACTIVITY == 089900 ~ "Professional and Personal Services",
    ACTIVITY == 089999 ~ "Professional and personal services",
    ACTIVITY == 090000 ~ "Household Services",
    ACTIVITY == 090100 ~ "Household Services (not done by self)",
    ACTIVITY == 090101 ~ "Using interior cleaning services",
    ACTIVITY == 090102 ~ "Using meal preparation services",
    ACTIVITY == 090103 ~ "Using clothing repair and cleaning services",
    ACTIVITY == 090104 ~ "Waiting associated with using household services",
    ACTIVITY == 090199 ~ "Using household services",
    ACTIVITY == 090200 ~ "Home MaintenanceRepairDecorationand Construction (not done by self)",
    ACTIVITY == 090201 ~ "Using home maint/repair/décor/construction services",
    ACTIVITY == 090202 ~ "Wtg assoc w/ home main/repair/décor/constr",
    ACTIVITY == 090299 ~ "Using home maint/repair/décor/constr services ",
    ACTIVITY == 090300 ~ "Pet Services (not done by self and not veterinary care)",
    ACTIVITY == 090301 ~ "Using pet services",
    ACTIVITY == 090302 ~ "Waiting associated with pet services",
    ACTIVITY == 090399 ~ "Using pet services",
    ACTIVITY == 090400 ~ "Lawn and Garden Services (not done by self)",
    ACTIVITY == 090401 ~ "Using lawn and garden services",
    ACTIVITY == 090402 ~ "Waiting assoc with using lawn and garden services",
    ACTIVITY == 090499 ~ "Using lawn and garden services",
    ACTIVITY == 090500 ~ "Vehicle Maintenance and Repair Services (not done by self)",
    ACTIVITY == 090501 ~ "Using vehicle maintenance or repair services",
    ACTIVITY == 090502 ~ "Waiting assoc with vehicle main. or repair services",
    ACTIVITY == 090599 ~ "Using vehicle maint. and repair services",
    ACTIVITY == 099900 ~ "Household Services",
    ACTIVITY == 099999 ~ "Using household services",
    ACTIVITY == 100000 ~ "Government Services and Civic Obligations",
    ACTIVITY == 100100 ~ "Using Government Services",
    ACTIVITY == 100101 ~ "Using police and fire services",
    ACTIVITY == 100102 ~ "Using social services",
    ACTIVITY == 100103 ~ "Obtaining licenses and paying fines, fees, taxes",
    ACTIVITY == 100199 ~ "Using government services",
    ACTIVITY == 100200 ~ "Civic obligations and participation",
    ACTIVITY == 100201 ~ "Civic obligations and participation",
    ACTIVITY == 100299 ~ "Civic obligations and participation",
    ACTIVITY == 100300 ~ "Waiting Associated with Government Services or Civic Obligations",
    ACTIVITY == 100303 ~ "Waiting assoc w/civic obligations and participation",
    ACTIVITY == 100304 ~ "Waiting associated with using government services",
    ACTIVITY == 100399 ~ "Wtg assoc w/govt services or civic obligations",
    ACTIVITY == 100400 ~ "Security Procedures Related to Government Services or Civic Obligations",
    ACTIVITY == 100401 ~ "Sec procedures related to govt services/civic obligations",
    ACTIVITY == 100499 ~ "Sec procs related to govt services/civic obligations",
    ACTIVITY == 109900 ~ "Government Services",
    ACTIVITY == 109999 ~ "Government services",
    ACTIVITY == 110000 ~ "Eating and Drinking",
    ACTIVITY == 110100 ~ "Eating and Drinking",
    ACTIVITY == 110101 ~ "Eating and drinking",
    ACTIVITY == 110199 ~ "Eating and drinking",
    ACTIVITY == 110200 ~ "Waiting Associated with Eating and Drinking",
    ACTIVITY == 110201 ~ "Waiting associated w/eating and drinking",
    ACTIVITY == 110299 ~ "Waiting associated with eating and drinking",
    ACTIVITY == 119900 ~ "Eating and Drinking",
    ACTIVITY == 119999 ~ "Eating and drinking",
    ACTIVITY == 120000 ~ "SocializingRelaxingand Leisure",
    ACTIVITY == 120100 ~ "Socializing and Communicating",
    ACTIVITY == 120101 ~ "Socializing and communicating with others",
    ACTIVITY == 120199 ~ "Socializing and communicating",
    ACTIVITY == 120200 ~ "Attending or Hosting Social Events",
    ACTIVITY == 120201 ~ "Attending or hosting parties/receptions/ceremonies",
    ACTIVITY == 120202 ~ "Attending meetings for personal interest (not volunteering)",
    ACTIVITY == 120299 ~ "Attending/hosting social events",
    ACTIVITY == 120300 ~ "Relaxing and Leisure",
    ACTIVITY == 120301 ~ "Relaxing thinking",
    ACTIVITY == 120302 ~ "Tobacco and drug use",
    ACTIVITY == 120303 ~ "Television and movies (not religious)",
    ACTIVITY == 120304 ~ "Television (religious)",
    ACTIVITY == 120305 ~ "Listening to the radio",
    ACTIVITY == 120306 ~ "Listening to/playing music (not radio)",
    ACTIVITY == 120307 ~ "Playing games",
    ACTIVITY == 120308 ~ "Computer use for leisure (exc. Games)",
    ACTIVITY == 120309 ~ "Arts and crafts as a hobby",
    ACTIVITY == 120310 ~ "Collecting as a hobby",
    ACTIVITY == 120311 ~ "Hobbiesexcept arts and crafts and collecting",
    ACTIVITY == 120312 ~ "Reading for personal interest",
    ACTIVITY == 120313 ~ "Writing for personal interest",
    ACTIVITY == 120399 ~ "Relaxing and leisure",
    ACTIVITY == 120400 ~ "Arts and Entertainment (other than sports)",
    ACTIVITY == 120401 ~ "Attending performing arts",
    ACTIVITY == 120402 ~ "Attending museums",
    ACTIVITY == 120403 ~ "Attending movies/film",
    ACTIVITY == 120404 ~ "Attending gambling establishments",
    ACTIVITY == 120405 ~ "Security procedures related to arts and entertainment",
    ACTIVITY == 120499 ~ "Arts and entertainment",
    ACTIVITY == 120500 ~ "Waiting Associated with Socializing Relaxing and Leisure",
    ACTIVITY == 120501 ~ "Waiting assoc. w/socializing and communicating",
    ACTIVITY == 120502 ~ "Waiting assoc. w/attending/hosting social events",
    ACTIVITY == 120503 ~ "Waiting associated with relaxing/leisure",
    ACTIVITY == 120504 ~ "Waiting associated with arts and entertainment",
    ACTIVITY == 120599 ~ "Waiting associated with socializing",
    ACTIVITY == 129900 ~ "SocializingRelaxingand Leisure",
    ACTIVITY == 129999 ~ "Socializingrelaxingand leisure",
    ACTIVITY == 130000 ~ "SportsExerciseand Recreation",
    ACTIVITY == 130100 ~ "Participating in SportsExerciseor Recreation",
    ACTIVITY == 130101 ~ "Doing aerobics",
    ACTIVITY == 130102 ~ "Playing baseball",
    ACTIVITY == 130103 ~ "Playing basketball",
    ACTIVITY == 130104 ~ "Biking",
    ACTIVITY == 130105 ~ "Playing billiards",
    ACTIVITY == 130106 ~ "Boating",
    ACTIVITY == 130107 ~ "Bowling",
    ACTIVITY == 130108 ~ "Climbing spelunking caving",
    ACTIVITY == 130109 ~ "Dancing",
    ACTIVITY == 130110 ~ "Participating in equestrian sports",
    ACTIVITY == 130111 ~ "Fencing",
    ACTIVITY == 130112 ~ "Fishing",
    ACTIVITY == 130113 ~ "Playing football",
    ACTIVITY == 130114 ~ "Golfing",
    ACTIVITY == 130115 ~ "Doing gymnastics",
    ACTIVITY == 130116 ~ "Hiking",
    ACTIVITY == 130117 ~ "Playing hockey",
    ACTIVITY == 130118 ~ "Hunting",
    ACTIVITY == 130119 ~ "Participating in martial arts",
    ACTIVITY == 130120 ~ "Playing racquet sports",
    ACTIVITY == 130121 ~ "Participating in rodeo competitions",
    ACTIVITY == 130122 ~ "Rollerblading",
    ACTIVITY == 130123 ~ "Playing rugby",
    ACTIVITY == 130124 ~ "Running",
    ACTIVITY == 130125 ~ "Skiing ice skating snowboarding",
    ACTIVITY == 130126 ~ "Playing soccer",
    ACTIVITY == 130127 ~ "Playing softball",
    ACTIVITY == 130128 ~ "Using cardiovascular equipment",
    ACTIVITY == 130129 ~ "Vehicle touring/racing",
    ACTIVITY == 130130 ~ "Playing volleyball",
    ACTIVITY == 130131 ~ "Walking",
    ACTIVITY == 130132 ~ "Participating in water sports",
    ACTIVITY == 130133 ~ "Weightlifting/strength training",
    ACTIVITY == 130134 ~ "Working outunspecified",
    ACTIVITY == 130135 ~ "Wrestling",
    ACTIVITY == 130136 ~ "Doing yoga",
    ACTIVITY == 130199 ~ "Playing sports",
    ACTIVITY == 130200 ~ "Attending Sports or Recreational Events",
    ACTIVITY == 130201 ~ "Watching aerobics",
    ACTIVITY == 130202 ~ "Watching baseball",
    ACTIVITY == 130203 ~ "Watching basketball",
    ACTIVITY == 130204 ~ "Watching biking",
    ACTIVITY == 130205 ~ "Watching billiards",
    ACTIVITY == 130206 ~ "Watching boating",
    ACTIVITY == 130207 ~ "Watching bowling",
    ACTIVITY == 130208 ~ "Watching climbing spelunking caving",
    ACTIVITY == 130209 ~ "Watching dancing",
    ACTIVITY == 130210 ~ "Watching equestrian sports",
    ACTIVITY == 130211 ~ "Watching fencing",
    ACTIVITY == 130212 ~ "Watching fishing",
    ACTIVITY == 130213 ~ "Watching football",
    ACTIVITY == 130214 ~ "Watching golfing",
    ACTIVITY == 130215 ~ "Watching gymnastics",
    ACTIVITY == 130216 ~ "Watching hockey",
    ACTIVITY == 130217 ~ "Watching martial arts",
    ACTIVITY == 130218 ~ "Watching racquet sports",
    ACTIVITY == 130219 ~ "Watching rodeo competitions",
    ACTIVITY == 130220 ~ "Watching rollerblading",
    ACTIVITY == 130221 ~ "Watching rugby",
    ACTIVITY == 130222 ~ "Watching running",
    ACTIVITY == 130223 ~ "Watching skiing ice skating snowboarding",
    ACTIVITY == 130224 ~ "Watching soccer",
    ACTIVITY == 130225 ~ "Watching softball",
    ACTIVITY == 130226 ~ "Watching vehicle touring/racing",
    ACTIVITY == 130227 ~ "Watching volleyball",
    ACTIVITY == 130228 ~ "Watching walking",
    ACTIVITY == 130229 ~ "Watching water sports",
    ACTIVITY == 130230 ~ "Watching weightlifting/strength training",
    ACTIVITY == 130231 ~ "Watching people working out",
    ACTIVITY == 130232 ~ "Watching wrestling",
    ACTIVITY == 130299 ~ "Attending sporting events",
    ACTIVITY == 130300 ~ "Waiting Associated with SportsExerciseand Recreation",
    ACTIVITY == 130301 ~ "Waiting related to playing sports or exercising",
    ACTIVITY == 130302 ~ "Waiting related to attending sporting events",
    ACTIVITY == 130399 ~ "Wtg assoc with sportsexerciseand rec",
    ACTIVITY == 130400 ~ "Security Procedures Related to SportsExerciseand Recreation",
    ACTIVITY == 130401 ~ "Security related to playing sports or exercising",
    ACTIVITY == 130402 ~ "Security related to attending sporting events",
    ACTIVITY == 130499 ~ "Sec related to sportsexerciseand rec",
    ACTIVITY == 139900 ~ "SportsExerciseand Recreation",
    ACTIVITY == 139999 ~ "Sportsexerciseand recreation",
    ACTIVITY == 140000 ~ "Religious and Spiritual Activities",
    ACTIVITY == 140100 ~ "Religious or Spiritual Practices",
    ACTIVITY == 140101 ~ "Attending religious services",
    ACTIVITY == 140102 ~ "Participation in religious practices",
    ACTIVITY == 140103 ~ "Waiting assoc w/religious and spiritual activities",
    ACTIVITY == 140104 ~ "Sec procedures related to relig and spiritual activities",
    ACTIVITY == 140105 ~ "Religious education activities (2007+)",
    ACTIVITY == 149900 ~ "Religious and Spiritual Activities",
    ACTIVITY == 149999 ~ "Religious and spiritual activities",
    ACTIVITY == 150000 ~ "Volunteer Activities",
    ACTIVITY == 150100 ~ "Administrative and Support Activities",
    ACTIVITY == 150101 ~ "Computer use",
    ACTIVITY == 150102 ~ "Organizing and preparing",
    ACTIVITY == 150103 ~ "Reading",
    ACTIVITY == 150104 ~ "Telephone calls (except hotline counseling)",
    ACTIVITY == 150105 ~ "Writing",
    ACTIVITY == 150106 ~ "Fundraising",
    ACTIVITY == 150199 ~ "Administrative and support activities",
    ACTIVITY == 150200 ~ "Social Service and Care Activities (except medical)",
    ACTIVITY == 150201 ~ "Food preparationpresentationclean-up",
    ACTIVITY == 150202 ~ "Collecting and delivering clothing and other goods",
    ACTIVITY == 150203 ~ "Providing care",
    ACTIVITY == 150204 ~ "Teachingleadingcounselingmentoring",
    ACTIVITY == 150299 ~ "Social service and care activities",
    ACTIVITY == 150300 ~ "Indoor and Outdoor MaintenanceBuildingand Clean-Up Activities",
    ACTIVITY == 150301 ~ "Building houseswildlife sitesand other structures",
    ACTIVITY == 150302 ~ "Indoor and outdoor maintenancerepairand clean-up",
    ACTIVITY == 150399 ~ "Indoor and outdoor maintbldg and clean-up",
    ACTIVITY == 150400 ~ "Participating in Performance and Cultural Activities",
    ACTIVITY == 150401 ~ "Performing",
    ACTIVITY == 150402 ~ "Serving at volunteer events and cultural activities",
    ACTIVITY == 150499 ~ "Participating performancecultural act.",
    ACTIVITY == 150500 ~ "Attending MeetingsConferencesand Training",
    ACTIVITY == 150501 ~ "Attending meetingsconferencesand training",
    ACTIVITY == 150599 ~ "Attending mtgs conferencesand training",
    ACTIVITY == 150600 ~ "Public Health and Safety Activities",
    ACTIVITY == 150601 ~ "Public health activities",
    ACTIVITY == 150602 ~ "Public safety activities",
    ACTIVITY == 150699 ~ "Public health and safety activities",
    ACTIVITY == 150700 ~ "Waiting Associated with Volunteer Activities",
    ACTIVITY == 150701 ~ "Waiting associated with volunteer activities",
    ACTIVITY == 150799 ~ "Waiting assoc with volunteer activities",
    ACTIVITY == 150800 ~ "Security Procedures Related to Volunteer Activities",
    ACTIVITY == 150801 ~ "Security procedures related to volunteer activities (2007+)",
    ACTIVITY == 150899 ~ "Security proecdures related to voluteer activities",
    ACTIVITY == 159900 ~ "Volunteer Activities",
    ACTIVITY == 159999 ~ "Volunteer activities",
    ACTIVITY == 160000 ~ "Telephone Calls",
    ACTIVITY == 160100 ~ "Telephone Calls (to or from)",
    ACTIVITY == 160101 ~ "Telephone calls to/from family members",
    ACTIVITY == 160102 ~ "Phone calls to/from friendsneighbors",
    ACTIVITY == 160103 ~ "Telephone calls to/from education services providers",
    ACTIVITY == 160104 ~ "Telephone calls to/from salespeople",
    ACTIVITY == 160105 ~ "Phone calls to/from profpersonal services providers",
    ACTIVITY == 160106 ~ "Phone calls to/from household services providers",
    ACTIVITY == 160107 ~ "Phone calls to/from child or adult care providers",
    ACTIVITY == 160108 ~ "Telephone calls to/from government officials",
    ACTIVITY == 160199 ~ "Telephone calls (to or from)",
    ACTIVITY == 160200 ~ "Waiting Associated with Telephone Calls",
    ACTIVITY == 160201 ~ "Waiting associated with telephone calls",
    ACTIVITY == 160299 ~ "Waiting associated with telephone calls",
    ACTIVITY == 169900 ~ "Telephone Calls",
    ACTIVITY == 169999 ~ "Telephone calls",
    ACTIVITY == 180000 ~ "Traveling",
    ACTIVITY == 180100 ~ "Travel Related to Personal Care",
    ACTIVITY == 180101 ~ "Travel related to personal care",
    ACTIVITY == 180199 ~ "Travel related to personal care",
    ACTIVITY == 180200 ~ "Travel Related to Household Activities",
    ACTIVITY == 180201 ~ "Travel related to housework",
    ACTIVITY == 180202 ~ "Travel related to food and drink prep",
    ACTIVITY == 180203 ~ "Travel related to int. maintrepairand decoration",
    ACTIVITY == 180204 ~ "Travel related to ext. maintrepairand decoration",
    ACTIVITY == 180205 ~ "Travel related to lawngardenand houseplants",
    ACTIVITY == 180206 ~ "Travel related to care for animals (not vet care)",
    ACTIVITY == 180207 ~ "Travel related to vehicle care and maint (by self)",
    ACTIVITY == 180208 ~ "Trvl rel to apptooltoy set-uprepairand maint",
    ACTIVITY == 180209 ~ "Travel related to household management",
    ACTIVITY == 180299 ~ "Travel related to household activities",
    ACTIVITY == 180300 ~ "Travel Related to Caring for and Helping Household Members",
    ACTIVITY == 180301 ~ "Travel related to caring for and helping household children",
    ACTIVITY == 180302 ~ "Travel related to caring for and helping household children",
    ACTIVITY == 180303 ~ "Travel related to household childrens education",
    ACTIVITY == 180304 ~ "Travel related to household childrens health",
    ACTIVITY == 180305 ~ "Travel related to caring for household adults",
    ACTIVITY == 180306 ~ "Travel related to helping household adults",
    ACTIVITY == 180307 ~ "Travel related to caring for and helping household adults",
    ACTIVITY == 180399 ~ "Trvl related to caring forhelping household members",
    ACTIVITY == 180400 ~ "Travel Related to Caring for and Helping Non-Household Members",
    ACTIVITY == 180401 ~ "Trvl rel to caring for and helping Non-Household kidsinclusive",
    ACTIVITY == 180402 ~ "Trvl rel to caring for and helping Non-Household kids",
    ACTIVITY == 180403 ~ "Travel related to Non-Household childrens education",
    ACTIVITY == 180404 ~ "Travel related to Non-Household childrens health",
    ACTIVITY == 180405 ~ "Travel related to caring for Non-Household adults",
    ACTIVITY == 180406 ~ "Travel related to helping Non-Household adults",
    ACTIVITY == 180407 ~ "Travel related to caring forhelping Non-Household adults",
    ACTIVITY == 180499 ~ "Trvl related to caring forhelping Non-Household",
    ACTIVITY == 180500 ~ "Travel Related to Work",
    ACTIVITY == 180501 ~ "Travel related to working",
    ACTIVITY == 180502 ~ "Travel related to work-related activities",
    ACTIVITY == 180503 ~ "Travel related to income-generating activities",
    ACTIVITY == 180504 ~ "Travel related to job search and interviewing",
    ACTIVITY == 180599 ~ "Travel related to work",
    ACTIVITY == 180600 ~ "Travel Related to Education",
    ACTIVITY == 180601 ~ "Travel related to taking class",
    ACTIVITY == 180602 ~ "Travel to extracurricular activities (ex. Sports)",
    ACTIVITY == 180603 ~ "Travel related to research/homework",
    ACTIVITY == 180604 ~ "Travel related to registration/admin activities",
    ACTIVITY == 180605 ~ "Education-related travelnot commuting",
    ACTIVITY == 180699 ~ "Education travel",
    ACTIVITY == 180700 ~ "Travel Related to Consumer Purchases",
    ACTIVITY == 180701 ~ "Traveling to/from the grocery store",
    ACTIVITY == 180702 ~ "Travel related to other shopping",
    ACTIVITY == 180703 ~ "Travel related to purchasing food (not groceries)",
    ACTIVITY == 180704 ~ "Travel related to shopping",
    ACTIVITY == 180705 ~ "Traveling to/from gas station",
    ACTIVITY == 180799 ~ "Travel related to consumer purchases",
    ACTIVITY == 180800 ~ "Travel Related to Using Professional and Personal Care Services",
    ACTIVITY == 180801 ~ "Travel related to using childcare services",
    ACTIVITY == 180802 ~ "Travel related to using financial services and banking",
    ACTIVITY == 180803 ~ "Travel related to using legal services",
    ACTIVITY == 180804 ~ "Travel related to using medical services",
    ACTIVITY == 180805 ~ "Travel related to using personal care services",
    ACTIVITY == 180806 ~ "Travel related to using real estate services",
    ACTIVITY == 180807 ~ "Travel related to using veterinary services",
    ACTIVITY == 180899 ~ "Travel related to using profpersonal care services ",
    ACTIVITY == 180900 ~ "Travel Related to Using Household Services",
    ACTIVITY == 180901 ~ "Travel related to using household services",
    ACTIVITY == 180902 ~ "Trvl rel to using home maint etc services",
    ACTIVITY == 180903 ~ "Travel related to using pet services (not vet)",
    ACTIVITY == 180904 ~ "Travel related to using lawn and garden services",
    ACTIVITY == 180905 ~ "Trvl rel to using vehicle maint and repair services",
    ACTIVITY == 180999 ~ "Travel related to using household services",
    ACTIVITY == 181000 ~ "Travel Related to Using Government Services and Civic Obligations",
    ACTIVITY == 181001 ~ "Travel related to using government services",
    ACTIVITY == 181002 ~ "Travel related to civic obligations and participation",
    ACTIVITY == 181099 ~ "Travel related to govt services and civic obligations",
    ACTIVITY == 181100 ~ "Travel Related to Eating and Drinking",
    ACTIVITY == 181101 ~ "Travel related to eating and drinking",
    ACTIVITY == 181199 ~ "Travel related to eating and drinking",
    ACTIVITY == 181200 ~ "Travel Related to SocializingRelaxingand Leisure",
    ACTIVITY == 181201 ~ "Travel related to socializing and communicating",
    ACTIVITY == 181202 ~ "Trvl related to attending or hosting social events",
    ACTIVITY == 181203 ~ "Travel related to relaxing and leisure (20032004)",
    ACTIVITY == 181204 ~ "Travel related to arts and entertainment",
    ACTIVITY == 181205 ~ "Travel as a form of entertainment",
    ACTIVITY == 181206 ~ "Travel related to relaxing and leisure (2005+)",
    ACTIVITY == 181299 ~ "Travel related to socializing elaxing leisure",
    ACTIVITY == 181300 ~ "Travel Related to Sports Exerciseand Recreation",
    ACTIVITY == 181301 ~ "Trvl rel to doing sports/exercise/recreation",
    ACTIVITY == 181302 ~ "Trvl rel to attending sporting/recreational events",
    ACTIVITY == 181399 ~ "Travel rel to sportsexerciserecreation",
    ACTIVITY == 181400 ~ "Travel Related to Religious or Spiritual Activities",
    ACTIVITY == 181401 ~ "Travel related to religious/spiritual practices",
    ACTIVITY == 181499 ~ "Travel related to religious/spiritual activities",
    ACTIVITY == 181500 ~ "Travel Related to Volunteering",
    ACTIVITY == 181501 ~ "Travel related to volunteering",
    ACTIVITY == 181599 ~ "Travel related to volunteer activities",
    ACTIVITY == 181600 ~ "Travel Related to Phone Calls",
    ACTIVITY == 181601 ~ "Travel related to phone calls",
    ACTIVITY == 181699 ~ "Travel related to phone calls",
    ACTIVITY == 181800 ~ "Security Procedures Related to Traveling",
    ACTIVITY == 181801 ~ "Security procedures related to traveling",
    ACTIVITY == 181899 ~ "Security procedures related to traveling",
    ACTIVITY == 189900 ~ "Traveling",
    ACTIVITY == 189999 ~ "Traveling",
    ACTIVITY == 500000 ~ "Data Codes",
    ACTIVITY == 500100 ~ "Unable to Code",
    ACTIVITY == 500101 ~ "Insufficient detail in verbatim",
    ACTIVITY == 500102 ~ "Recorded activity using incorrect words",
    ACTIVITY == 500103 ~ "Missing travel or destination",
    ACTIVITY == 500104 ~ "Recorded simultaneous activities incorrectly",
    ACTIVITY == 500105 ~ "Respondent refused to provide information",
    ACTIVITY == 500106 ~ "Gap/cant remember",
    ACTIVITY == 500107 ~ "Unable to code activity at 1st tier",
    ACTIVITY == 509900 ~ "Data codes",
    ACTIVITY == 509999 ~ "Data codes"
  ))
